/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  customerEmail?: string;
  items?: Array<{
    productId?: string;
    title?: string;
    quantity?: number;
    price?: number;
    _key: string;
  }>;
  total?: number;
  paymentStatus?: "pending" | "paid" | "failed";
  status?:
    | "placed"
    | "packed"
    | "out_for_delivery"
    | "delivered"
    | "cancelled"
    | "refunded";
  shippingAddress?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  paymentMethod?: "stripe" | "jazzcash" | "easypaisa";
};

export type Coupon = {
  _id: string;
  _type: "coupon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  code?: string;
  discountType?: "percentage" | "fixed";
  value?: number;
  isActive?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  quote?: string;
  rating?: number;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  buttonText?: string;
  buttonLink?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  secondaryImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  category?: CategoryReference;
  stock?: number;
  pH?: number;
  capacity?: string;
  material?: string;
  minerals?: Array<string>;
  idealUse?: "daily" | "sports" | "kids";
  isComingSoon?: boolean;
  variants?: Array<{
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price?: number;
    capacity?: string;
    pH?: number;
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Order
  | Coupon
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | BlogPost
  | Slug
  | Banner
  | CategoryReference
  | Product
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/app/cart/page.tsx
// Variable: COUPON_QUERY
// Query: *[_type == "coupon" && code == $code && isActive == true][0] {    code,    discountType,    value  }
export type COUPON_QUERY_RESULT = {
  code: string | null;
  discountType: "fixed" | "percentage" | null;
  value: number | null;
} | null;

// Source: ../web/src/app/dashboard/page.tsx
// Variable: CUSTOMER_ORDERS_QUERY
// Query: *[_type == "order" && customerEmail == $email] | order(_createdAt desc) {    _id,    orderNumber,    customerEmail,    items,    total,    paymentStatus,    status,    _createdAt  }
export type CUSTOMER_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  customerEmail: string | null;
  items: Array<{
    productId?: string;
    title?: string;
    quantity?: number;
    price?: number;
    _key: string;
  }> | null;
  total: number | null;
  paymentStatus: "failed" | "paid" | "pending" | null;
  status:
    | "cancelled"
    | "delivered"
    | "out_for_delivery"
    | "packed"
    | "placed"
    | "refunded"
    | null;
  _createdAt: string;
}>;

// Source: ../web/src/app/page.tsx
// Variable: HOMEPAGE_QUERY
// Query: {  "banners": *[_type == "banner"] | order(order asc) {    _id,    title,    subtitle,    buttonText,    buttonLink,    "imageUrl": image.asset->url  },  "products": *[_type == "product" && defined(slug.current)][0...8] {    _id,    title,    "slug": slug.current,    price,    description,    "imageUrl": image.asset->url,    "secondaryImageUrl": secondaryImage.asset->url,    capacity,    pH,    material,    minerals,    idealUse  },  "testimonials": *[_type == "testimonial"][0...3] {    _id,    name,    role,    quote,    rating,    "avatarUrl": avatar.asset->url  }}
export type HOMEPAGE_QUERY_RESULT = {
  banners: Array<{
    _id: string;
    title: string | null;
    subtitle: string | null;
    buttonText: string | null;
    buttonLink: string | null;
    imageUrl: string | null;
  }>;
  products: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    price: number | null;
    description: string | null;
    imageUrl: string | null;
    secondaryImageUrl: string | null;
    capacity: string | null;
    pH: number | null;
    material: string | null;
    minerals: Array<string> | null;
    idealUse: "daily" | "kids" | "sports" | null;
  }>;
  testimonials: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    quote: string | null;
    rating: number | null;
    avatarUrl: string | null;
  }>;
};

// Source: ../web/src/app/product/[slug]/page.tsx
// Variable: PRODUCT_DETAIL_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    price,    description,    "imageUrl": image.asset->url,    "secondaryImageUrl": secondaryImage.asset->url,    capacity,    pH,    material,    minerals,    idealUse  }
export type PRODUCT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  description: string | null;
  imageUrl: string | null;
  secondaryImageUrl: string | null;
  capacity: string | null;
  pH: number | null;
  material: string | null;
  minerals: Array<string> | null;
  idealUse: "daily" | "kids" | "sports" | null;
} | null;

// Source: ../web/src/app/product/[slug]/page.tsx
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && slug.current != $slug][0...3] {    _id,    title,    "slug": slug.current,    price,    description,    "imageUrl": image.asset->url,    capacity  }
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  description: string | null;
  imageUrl: string | null;
  capacity: string | null;
}>;

// Source: ../web/src/app/shop/page.tsx
// Variable: PRODUCTS_CATALOG_QUERY
// Query: *[_type == "product"] {    _id,    title,    "slug": slug.current,    price,    description,    "imageUrl": image.asset->url,    capacity,    "categoryTitle": category->title,    isComingSoon  }
export type PRODUCTS_CATALOG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  description: string | null;
  imageUrl: string | null;
  capacity: string | null;
  categoryTitle: string | null;
  isComingSoon: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "coupon" && code == $code && isActive == true][0] {\n    code,\n    discountType,\n    value\n  }\n': COUPON_QUERY_RESULT;
    '\n  *[_type == "order" && customerEmail == $email] | order(_createdAt desc) {\n    _id,\n    orderNumber,\n    customerEmail,\n    items,\n    total,\n    paymentStatus,\n    status,\n    _createdAt\n  }\n': CUSTOMER_ORDERS_QUERY_RESULT;
    '{\n  "banners": *[_type == "banner"] | order(order asc) {\n    _id,\n    title,\n    subtitle,\n    buttonText,\n    buttonLink,\n    "imageUrl": image.asset->url\n  },\n  "products": *[_type == "product" && defined(slug.current)][0...8] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    description,\n    "imageUrl": image.asset->url,\n    "secondaryImageUrl": secondaryImage.asset->url,\n    capacity,\n    pH,\n    material,\n    minerals,\n    idealUse\n  },\n  "testimonials": *[_type == "testimonial"][0...3] {\n    _id,\n    name,\n    role,\n    quote,\n    rating,\n    "avatarUrl": avatar.asset->url\n  }\n}': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    description,\n    "imageUrl": image.asset->url,\n    "secondaryImageUrl": secondaryImage.asset->url,\n    capacity,\n    pH,\n    material,\n    minerals,\n    idealUse\n  }\n': PRODUCT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current != $slug][0...3] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    description,\n    "imageUrl": image.asset->url,\n    capacity\n  }\n': RELATED_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product"] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    description,\n    "imageUrl": image.asset->url,\n    capacity,\n    "categoryTitle": category->title,\n    isComingSoon\n  }\n': PRODUCTS_CATALOG_QUERY_RESULT;
  }
}
